trigger:
- main   # ya jis branch se tu pipeline run karna chahta hai

pool:
  vmImage: ubuntu-latest

variables:
  EC2_USER: "ec2-user"           # Amazon Linux ka default user
  EC2_HOST: "3.85.167.56"        # Tera EC2 public IP
  EC2_KEY: "$(ssh_key)"          # Azure Library me stored PEM key (secure variable)
  REMOTE_FILE: "/home/ec2-user/text.txt"   # EC2 pe file ka path
  LOCAL_COPY: "$(Build.ArtifactStagingDirectory)/text.txt"  # Azure pipeline me local path

steps:
# Step 1: Install SSH client
- task: Bash@3
  displayName: 'Install SSH Client'
  inputs:
    targetType: inline
    script: |
      sudo apt-get update -y
      sudo apt-get install -y openssh-client

# Step 2: Create SSH private key from Azure variable
- task: Bash@3
  displayName: 'Setup SSH Private Key'
  inputs:
    targetType: inline
    script: |
      echo "$EC2_KEY" > private_key.pem
      chmod 600 private_key.pem
      echo "✅ SSH key created successfully."

# Step 3: Copy file FROM EC2 to pipeline workspace
- task: Bash@3
  displayName: 'Download text.txt from EC2'
  inputs:
    targetType: inline
    script: |
      echo "📥 Downloading file from EC2..."
      scp -vvv -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST:$REMOTE_FILE $LOCAL_COPY
      echo "✅ File downloaded successfully to $LOCAL_COPY"

# Step 4: Publish the downloaded file as pipeline artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: text.txt'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'EC2File'
    publishLocation: 'Container'
